# Cabeceras de Seguridad Obligatorias
Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains"
Header always set Content-Security-Policy "default-src 'self';"

# Bloqueo de listado de directorios
<Directory /var/www/html>
    Options -Indexes
</Directory>