server {
    listen 80;
    listen 443 ssl;
    server_name localhost;

    # Rutas a los certificados generados en el Dockerfile
    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    # --- HARDENING ---
    server_tokens off; # Oculta la versión de Nginx
    
    # Cabeceras de seguridad optimizadas
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
    add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline';" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;

    root /var/www/html;
    index index.php index.html;

    # --- AUTENTICACIÓN GLOBAL ---
    auth_basic "Acceso Restringido - Práctica 5";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location / {
        try_files $uri $uri/ =404;
    }

    # --- CONFIGURACIÓN PHP-FPM VÍA TCP ---
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000; # Comunicación TCP para evitar errores 502
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        
        # Nginx requiere repetir las cabeceras dentro de los bloques location si se usan directivas add_header
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
        add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline';" always;
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
    }
}