Include /etc/apache2/conf-available/hardening.conf
Include /etc/apache2/conf-available/security-headers.conf

<VirtualHost *:80>
    ServerName www.victorteleanu.com
    Redirect permanent / https://www.victorteleanu.com:9449/
</VirtualHost>

<VirtualHost *:443>
    ServerName www.victorteleanu.com
    DocumentRoot /var/www/html

    SSLEngine on
    SSLCertificateFile /etc/apache2/ssl/apache.crt
    SSLCertificateKeyFile /etc/apache2/ssl/apache.key

    # PUNTOS 2 y 5 FUSIONADOS:
    <Directory /var/www/html>
        # 2. Desactivar listado de directorios, SSI y .htaccess
        Options -Indexes -Includes
        AllowOverride None
        
        # 5. Limitar métodos HTTP
        <LimitExcept GET POST HEAD>
            Require all denied
        </LimitExcept>
        
        Require all granted
    </Directory>
</VirtualHost>